[package]
name = "rlumod"
version = "0.1.2"
edition = "2024"
rust-version = "1.85"
description = "Safe, no_std matrix updates and linear solves using the LUmod algorithm"
repository = "https://github.com/daisuke-nagao/rlumod"
keywords = ["linear-algebra", "LUmod", "matrix", "no-std"]
categories = ["algorithms", "no-std"]
license = "MIT"
exclude = ["/c-ffi"]

[features]
default = []
lumod-c = []

[dependencies]

[package.metadata.docs.rs]
all-features = true

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dev-dependencies]
wasm-bindgen-test = "0.3"

[[example]]
name = "lumod-c"
path = "examples/lumod-c.rs"
required-features = ["lumod-c"]
