[package]
name = "rlumod-staticlib-consumer"
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
publish = false

[lib]
crate-type = ["staticlib"]

[features]
default = ["one-based", "zero-based"]
one-based = ["rlumod/c-ffi-one-based"]
zero-based = ["rlumod/c-ffi-zero-based"]

[dependencies]
rlumod = { path = "../..", default-features = false }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
