#include <lumod-c/lumod_dense.h>

#include <math.h>

#ifdef LUMOD_C_ORIGINAL
#include <myblas.h>
#endif

static int close_enough(double actual, double expected) {
  return fabs(actual - expected) <= 1.0e-12;
}

int main(void) {
#ifdef LUMOD_C_ORIGINAL
  init_BLAS();
#endif
  const double eps = 2.22e-16;
  double L[6] = {91.0, 0.0, 0.0, 0.0, 0.0, 92.0};
  double U[5] = {93.0, 0.0, 0.0, 0.0, 94.0};
  double y[4] = {95.0, 0.0, 0.0, 96.0};
  double z[4] = {97.0, 0.0, 0.0, 98.0};
  double w[4] = {99.0, 0.0, 0.0, 100.0};

  y[1] = z[1] = 4.0;
  LUmod(1, 2, 1, 0, 0, L, U, y, z, w);
  y[1] = 1.0;
  y[2] = 5.0;
  z[1] = 2.0;
  z[2] = 5.0;
  LUmod(1, 2, 2, 0, 0, L, U, y, z, w);

  y[1] = 1.0;
  y[2] = 5.0;
  LUmod(3, 2, 2, 2, 0, L, U, y, z, w);
  z[1] = 2.0;
  z[2] = 5.0;
  LUmod(2, 2, 2, 0, 2, L, U, y, z, w);
  /* Golden state generated by the original dense lumod-c implementation. */
  if (L[1] != 1.0 || L[2] != 0.0 || L[3] != -0.25 || L[4] != 1.0 ||
      U[1] != 4.0 || U[2] != 2.0 || U[3] != 4.5 || y[1] != 0.0 ||
      y[2] != 4.5 || z[1] != 2.0 || z[2] != 5.0 || w[1] != 2.0 ||
      w[2] != 4.5) {
    return 6;
  }

  {
    double rhs[4] = {101.0, 8.0, 11.0, 102.0};
    double work[4] = {103.0, 0.0, 0.0, 104.0};
    Lprod(1, 2, 2, L, rhs, work);
    rhs[1] = work[1];
    rhs[2] = work[2];
    Usolve(1, 2, 2, U, rhs);
    if (!close_enough(rhs[1], 1.0) || !close_enough(rhs[2], 2.0) ||
        rhs[0] != 101.0 || rhs[3] != 102.0 || work[0] != 103.0 ||
        work[3] != 104.0) {
      return 1;
    }
  }

  {
    double rhs[4] = {105.0, 6.0, 12.0, 106.0};
    double work[4] = {107.0, 0.0, 0.0, 108.0};
    Usolve(2, 2, 2, U, rhs);
    Lprod(2, 2, 2, L, rhs, work);
    if (!close_enough(work[1], 1.0) || !close_enough(work[2], 2.0)) {
      return 2;
    }
  }

  {
    double lower[6] = {109.0, 1.0, 0.0, 0.0, 1.0, 110.0};
    double upper[5] = {111.0, 1.0, 0.0, 1.0, 112.0};
    double spike[4] = {113.0, 2.0, 3.0, 114.0};
    double column[4] = {115.0, 1.0, 2.0, 116.0};
    int last = 2;
    LUforw(1, 2, 2, 2, 2, eps, lower, upper, spike);
    LUback(1, &last, 2, 2, 2, eps, lower, upper, spike, column);
    if (last < 1 || last > 2 || lower[0] != 109.0 || lower[5] != 110.0 ||
        upper[0] != 111.0 || upper[4] != 112.0) {
      return 3;
    }
  }

  {
    double first[4] = {119.0, 1.0, 2.0, 117.0};
    double second[4] = {120.0, 3.0, 4.0, 118.0};
    double scalar_x = 4.0;
    double scalar_y = 2.0;
    double cs = 0.0;
    double sn = 0.0;
    elm(7, 2, first, second, -1.0, 0.5);
    elmgen(&scalar_x, &scalar_y, eps, &cs, &sn);
    if (first[0] != 119.0 || first[3] != 117.0 || second[0] != 120.0 ||
        second[3] != 118.0 || !close_enough(scalar_x, 4.0) ||
        scalar_y != 0.0 || cs != 0.0 || !close_enough(sn, -0.5)) {
      return 4;
    }
  }

  LUmod(4, 2, 2, 2, 2, L, U, y, z, w);
  if (L[0] != 91.0 || L[5] != 92.0 || U[0] != 93.0 || U[4] != 94.0 ||
      y[0] != 95.0 || y[3] != 96.0 || z[0] != 97.0 || z[3] != 98.0 ||
      w[0] != 99.0 || w[3] != 100.0) {
    return 5;
  }
  return 0;
}
